# Generated by Django 5.2.1 on 2025-09-05 16:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(choices=[('aggregation', 'Aggregation & Pruning'), ('similarity', 'Recalculate Similarity'), ('trending_cache', 'Refresh Trending Cache')], max_length=50)),
                ('run_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='success', max_length=20)),
                ('details', models.TextField(blank=True)),
            ],
        ),
    ]
