# Generated by Django 5.2.1 on 2025-07-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='postinteraction',
            index=models.Index(fields=['post', 'viewed'], name='users_posti_post_id_63897e_idx'),
        ),
        migrations.AddIndex(
            model_name='postinteraction',
            index=models.Index(fields=['post', 'liked'], name='users_posti_post_id_f80598_idx'),
        ),
        migrations.AddIndex(
            model_name='postinteraction',
            index=models.Index(fields=['user', 'liked'], name='users_posti_user_id_fbca25_idx'),
        ),
    ]
