# Generated by Django 5.2.1 on 2025-07-04 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_updated_at'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpostactivity',
            options={'verbose_name_plural': 'User Post Activities'},
        ),
        migrations.RemoveField(
            model_name='userpostactivity',
            name='action_performed',
        ),
        migrations.RemoveField(
            model_name='userpostactivity',
            name='action_status',
        ),
        migrations.AddField(
            model_name='userpostactivity',
            name='action',
            field=models.CharField(choices=[('A', 'Added'), ('D', 'Deleted'), ('E', 'Edited'), ('U', 'Updated')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='userpostactivity',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpostactivity',
            name='reason',
            field=models.CharField(choices=[('typo', 'Fixed typos'), ('info', 'Added more information'), ('image', 'Updated image'), ('structure', 'Improved structure'), ('other', 'Other (please specify)')], default='A', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userpostactivity',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='blog.post'),
        ),
    ]
