# Generated by Django 5.2.1 on 2025-05-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='category_preferences',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='category_preferences',
            field=models.ManyToManyField(blank=True, to='blog.category'),
        ),
    ]
