# Generated by Django 5.2.1 on 2025-07-30 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_blog_catego_name_cb8828_idx'),
        ('users', '0002_postinteraction_users_posti_post_id_63897e_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam Content'), ('inappropriate', 'Inappropriate Content'), ('harassment', 'Harassment'), ('fake_news', 'Fake News/Misinformation'), ('copyright', 'Copyright Violation'), ('violence', 'Violence/Threats'), ('adult', 'Adult Content'), ('hate_speech', 'Hate Speech'), ('other', 'Other')], max_length=20)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_reports', to='blog.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filed_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
