# Generated by Django 5.2.1 on 2025-08-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_blog_catego_name_cb8828_idx'),
        ('users', '0003_postreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='category_preferences',
            field=models.ManyToManyField(blank=True, related_name='preferred_by_users', to='blog.category'),
        ),
    ]
