# Generated by Django 5.2.1 on 2025-07-05 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20250705_2155'),
        ('users', '0003_alter_userpostactivity_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postinteraction',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='blog.post'),
        ),
        migrations.AlterField(
            model_name='postinteraction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='postinteraction',
            unique_together={('user', 'post')},
        ),
    ]
