# Generated by Django 5.2.1 on 2025-09-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_status_recommendationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationlog',
            name='tier',
            field=models.IntegerField(choices=[(3, 'Engaged'), (2, 'Fresh'), (1, 'Trending'), (0, 'Explore')], default=0),
        ),
    ]
