# Generated by Django 5.2.1 on 2025-09-05 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_recommendationlog_tier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.IntegerField(choices=[(3, 'Engaged'), (2, 'Fresh/Trending'), (1, 'Exploration')], default=1)),
                ('date', models.DateField()),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='recommendationlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='recommendationlog',
            old_name='recommended_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='recommendationlog',
            name='clicked',
        ),
        migrations.RemoveField(
            model_name='recommendationlog',
            name='engaged',
        ),
        migrations.AlterField(
            model_name='recommendationlog',
            name='tier',
            field=models.IntegerField(choices=[(3, 'Engaged'), (2, 'Fresh/Trending'), (1, 'Exploration')], default=1),
        ),
        migrations.AddIndex(
            model_name='recommendationlog',
            index=models.Index(fields=['user', 'tier', 'created_at'], name='blog_recomm_user_id_801c53_idx'),
        ),
        migrations.AddField(
            model_name='recommendationstats',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='recommendationstats',
            index=models.Index(fields=['date', 'tier'], name='blog_recomm_date_e06885_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationstats',
            index=models.Index(fields=['user', 'date'], name='blog_recomm_user_id_6c9962_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recommendationstats',
            unique_together={('user', 'tier', 'date')},
        ),
    ]
