# Generated by Django 5.2.1 on 2025-09-05 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_recommendationstats_alter_recommendationlog_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recommendationstats',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='recommendationstats',
            name='user',
        ),
        migrations.DeleteModel(
            name='RecommendationLog',
        ),
        migrations.DeleteModel(
            name='RecommendationStats',
        ),
    ]
