# Generated by Django 5.2.1 on 2025-09-05 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_recommendationstats_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.IntegerField(choices=[(3, 'Engaged'), (2, 'Fresh/Trending'), (1, 'Exploration')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clicked', models.BooleanField(default=False)),
                ('engaged', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'tier', 'created_at'], name='blog_recomm_user_id_801c53_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecommendationStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.IntegerField(choices=[(3, 'Engaged'), (2, 'Fresh/Trending'), (1, 'Exploration')], default=1)),
                ('date', models.DateField()),
                ('count', models.IntegerField(default=0)),
                ('click_count', models.IntegerField(default=0)),
                ('engage_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'tier'], name='blog_recomm_date_e06885_idx'), models.Index(fields=['user', 'date'], name='blog_recomm_user_id_6c9962_idx')],
                'unique_together': {('user', 'tier', 'date')},
            },
        ),
    ]
